sudo: required

language: generic

services:
  - docker

# build image using Dockerfile.dev
before_install:
  - docker build -t s777610/docker-react -f Dockerfile.dev .

script:
  - docker run s777610/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-740907403078"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
