sudo: required
services:
  - docker

# build image using Dockerfile.dev
before_install:
  - docker build -t s777610/docker-react -f Dockerfile.dev .

script:
  - docker run s777610/docker-react npm run test -- --coverage
