version: "3"
services:
  # two containers, web and tests
  # this is for hosting dev server
  web:
    build:
      # tell docker that looking Dockerfile.dev as Dockerfile in . directory for building image
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # two volumes inside that container
    volumes:
      # don't try to map folder node_modules inside container
      - /app/node_modules
      # map local folder to /app insdie container
      - .:/app

  # this is for testing, rerun whenever volumes change
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
